Domain model
2021-msa-study/smartcloset pull request #9
Opened 2021-04-07 14:01 UTC by lyonmoon

1) MyClothing에 옷 등록하는 서비스
2) 옷장(+파티션) 등록하는 서비스
3) 옷을 옷장 내 Partition에 할당/해제하는 서비스
에 대한 코드 및 test case입니다.

2021-04-09 00:05 UTC, cloudeyes requested changes
아래 요청사항 의견 달아주시고 문제 없으면 변경부탁드립니다. 
변경 되면 리뷰 승인 하겠습니다.

2021-04-09 00:05 UTC, cloudeyes commented on tests/unit/test_myclothes.py
> +    myclothings.add_clothing(clothing01)
@lyonmoon @sjw451 `MyClothings` 클래스의 API 이름을 좀 바꿨으면 좋겠어요.

`add_clothing`, `update_clothing` 같이 뒤에 `_clothing`이 붙는걸 굳이 붙여야 하는 생각이 드네요. 코드에서 파라메터 타입으로 다 들어나니기도 하고 `MyClothings` 에서 `add` 라고 한다면 선명하게 `Clothing` 객체를 추가하겠다고 이해할 수 있으니까요.

반면, `Closet` 객체의 `add_partition` 의 `_partition` 은 붙여두어야 한다는 입장입니다. 옷장에 옷을 추가하는건지 파티션을 추가하는건지 `add` 라고만 하면 헷깔릴수 있으니까요.

2021-04-09 00:05 UTC, cloudeyes commented on tests/unit/test_myclothes.py
> +    myclothings.add_clothing(clothing01)
`Partition` 클래스의 API도 아래와 같이 바꾸는게 좋겠습니다. 파티션에 할당하는게 `Clothing` 이라는게 모호하지 않기때문에 바꾸는게 더 깔끔해 보입니다.

- `alloc_clothing` -> `allocate`
- `dealloc_clothing` -> `deallocate` 

```python
class Partition:
    def allocate(self, clothing: Clothing):
       ...

    def deallocate(self, clothing: Clothing):
        ...
```

2021-04-10 08:01 UTC, lyonmoon commented
요청하신 change requset를 반영하려하는데
pull request이후에는 push가 안되는데 본 pull requset건을 close후 수정하고 다시 request를해야할까요?

2021-04-10 08:14 UTC, cloudeyes commented
@lyonmoon 아... 제가 브랜치 보호정책을 리뷰중에는 푸시 못하게 걸어놔서 그런거 같은데 푸시 가능하도록 설정 바꿔놓을게요.

2021-04-10 11:46 UTC, cloudeyes commented
> 요청하신 change requset를 반영하려하는데
> pull request이후에는 push가 안되는데 본 pull requset건을 close후 수정하고 다시 request를해야할까요?

@lyonmoon 브랜치 머지 정책 조치했습니다! 다시한번 시도해보세요!

2021-04-11 02:28 UTC, lyonmoon commented on tests/unit/test_myclothes.py
> +    myclothings.add_clothing(clothing01)
초반에 네이밍룰을 잘 반영하는게 코드가 복잡해질수록 중요할거같습니다.
말씀하신부분 반영하여 수정하였습니다!

2021-04-17 03:16 UTC, cloudeyes approved these changes
승인 합니다.

2021-04-25 12:10 UTC, benzamin0 approved these changes

2021-04-25 12:32 UTC, merged